services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5433:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - 'my-network'

  minio:
    image: 'minio/minio:latest'
    container_name: 'minio'
    command: 'server /data --console-address ":9001"'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}'
    ports:
      - '9000:9000'
      - "9001:9001"
    volumes:
      - 'minio_data:/data'
    networks:
      - 'my-network'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    networks:
      - 'my-network'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  minio_data:
  redis_data:

networks:
  my-network:
    driver: bridge
