--liquibase formatted sql

--changeset AntonKulakov:1
--comment first migration
CREATE TABLE Users
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login varchar(100) NOT NULL UNIQUE,
    password varchar(255) NOT NULL
);

 INSERT INTO Users (login, password)
VALUES ('test_user1', 'test-password'),
       ('test_user2', 'test-password');
--rollback truncate table demo;